version: "3.1"
services:
    db:
        image: mysql
        container_name: mysql-wordpress
        restart: always
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: valenzuela21
            MYSQL_USER: wordpress
            MYSQL_ROOT_PASSWORD: valenzuela21
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - wpsite
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links: 
            - db
        ports:
            - 8080:80
        restart: always
        environment:
           PMA_HOST: db
           PMA_PORT: 3306
           PMA_ARBITRARY: 1
        networks:
            - wpsite
  
    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - '8000:80'
        restart: always
        volumes: ['./:/var/www/html']
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: dbname
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: valenzuela21
                   
        networks:
            - wpsite
networks:
    wpsite:            
volumes:
    persistent: